export const CART_ACTION_TYPES = {
    ADD_ITEM_TO_CART: 'cart/ADD_ITEM_TO_CART',
    DEL_ITEM_IN_CART: 'cart/DEL_ITEM_FROM_CART',
    CLEAR_ITEM_IN_CART: 'cart/CLEAR_ITEM_IN_CART',
    SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN'
}